ignoreGeneratedHeader = false
severity = "error"
confidence = 0.9
errorCode = 1
warningCode = 0

[rule.argument-limit]
  arguments = [10]
  severity = "warning"
[rule.blank-imports]
[rule.confusing-results]
  severity = "warning"
[rule.context-as-argument]
[rule.context-keys-type]
[rule.cyclomatic]
  arguments = [20]
[rule.deep-exit]
[rule.dot-imports]
[rule.empty-block]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.get-return]
[rule.if-return]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.modifies-parameter]
[rule.range]
[rule.receiver-naming]
[rule.struct-tag]
  severity = "warning"
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unnecessary-stmt]
[rule.unreachable-code]
[rule.unused-parameter]
  severity = "warning"
[rule.var-declaration]
